[project]
name = "controller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.124.0",
    "pydantic>=2.12.5",
    "uvicorn>=0.34.0",
]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "ruff>=0.14.8",
]
