[project]
name = "hpc-runner"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pdfplumber>=0.11.8",
    "pypdf>=6.4.1",
]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "ruff>=0.14.8",
]
